name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy code to remote server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "."
        target: ${{ secrets.DESTINATION_FOLDER }}

    # - name: Restart Docker containers
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.SERVER_IP }}
    #     username: ${{ secrets.SERVER_USER }}
    #     key: ${{ secrets.DEPLOY_KEY }}
    #     port: ${{ secrets.SSH_PORT }}
    #     script: |
    #       cd ${{ secrets.DESTINATION_FOLDER }}
    #       ./restart.sh